pie title Rol Bazli Is Gucu Dagilimi
  "Proje Yoneticisi" : 12
  "Is/Sistem Analisti" : 16
  "Backend Gelistirici" : 18
  "Mobil Gelistirici" : 18
  "Web Panel Gelistirici" : 12
  "DB ve DevOps" : 12
  "Test ve Kalite" : 12
